app = "bd-homepage-fucky"
primary_region = "nrt"

[env]
  SPRING_PROFILES_ACTIVE = "free"
  JAVA_OPTS = "-Xms32m -Xmx192m -XX:MaxMetaspaceSize=96m"
[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    type = "http"
    path = "/api/health"
    interval = "15s"
    timeout = "2s"
    grace_period = "180s"
