app = "bd-homepage-last"
primary_region = "nrt"

[env]
  JAVA_TOOL_OPTIONS = "-Xms16m -Xmx128m -XX:MaxMetaspaceSize=64m -XX:+UseSerialGC"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    type = "tcp"
    interval = "20s"
    timeout = "10s"
    grace_period = "420s"
