app = "bd-homepage-last"
primary_region = "nrt"

[env]
  JAVA_TOOL_OPTIONS = "-Xms16m -Xmx80m -XX:MaxMetaspaceSize=40m -Xss256k -XX:+UseSerialGC -Dspring.main.lazy-initialization=true -Dspring.jpa.open-in-view=false -Dspring.jmx.enabled=false"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    type = "tcp"
    interval = "30s"
    timeout = "10s"
    grace_period = "600s"
