app = "bd-homepage-last"
primary_region = "nrt"

[env]
  JAVA_OPTS = "-XX:MaxRAMPercentage=55 -XX:InitialRAMPercentage=15 -XX:+UseSerialGC -XX:MaxMetaspaceSize=96m"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    type = "tcp"
    interval = "20s"
    timeout = "10s"
    grace_period = "300s"
